# Generated by Django 3.0.4 on 2020-03-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.TextField(default=0),
        ),
    ]
