# Generated by Django 3.0.4 on 2020-04-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='Content',
            new_name='content',
        ),
    ]
