# Generated by Django 3.0.4 on 2020-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200401_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
