# Generated by Django 3.0.4 on 2020-04-01 07:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursecontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
