# Generated by Django 3.0.4 on 2020-04-01 07:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200401_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
