# Generated by Django 3.0.4 on 2020-04-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200401_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('signIn_bool', models.BooleanField(default=0)),
                ('signIn_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
