# Generated by Django 3.0.4 on 2020-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_coursesignin_signin_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesignin',
            name='signIn_time',
            field=models.DateField(auto_now=True),
        ),
    ]
