# Generated by Django 3.0.4 on 2020-04-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200403_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesignin',
            name='student_name',
            field=models.TextField(max_length=100),
        ),
    ]
