# Generated by Django 3.0.4 on 2020-04-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200403_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesignin',
            name='student_id',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
